version: '3.8'

services:
  discord-bot:
    container_name: cloudbot
    build: .
    image: cloudbot 
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - bot-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-cache
    networks:
      - bot-network
    restart: unless-stopped

networks:
    bot-network:
      driver: bridge 